name: CI
on:
  # schedule: [{cron: '0 0 * * *'}]
  pull_request:
  push:
    paths:
      - '**.agda'
      - '*.agda-lib'
      - '.github/workflows/**.yml'
    branches: [main]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: omelkonian/setup-agda@v2.2
        with:
          agda-version: 2.6.4.1
          stdlib-version: 1.7.2
          libraries: agda/agda2hs#f5ac455
          main: index
          deploy: ${{ github.ref == 'refs/heads/main' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ribbon: true
