name: CI
on:
  # schedule: [{cron: '0 0 * * *'}]
  pull_request:
  push:
    paths:
      - '**.agda'
      - '*.agda-lib'
      - '.github/workflows/**.yml'
    branches: [main]
permissions: 
  contents: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: omelkonian/setup-agda@master
        with:
          agda-version: 2.7.0.1
          stdlib-version: 2.2
          libraries: agda/agda2hs#v1.3
          main: index
          deploy: ${{ github.ref == 'refs/heads/main' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ribbon: true
